# Test against this version of Node.js
environment:
matrix:
#node.js
nodejs_version:"6"

#Install scripts. (runs after repo cloning)
install:
#Get the latest stale version of Node.js or io.js
px: Install-Product node $env:nodejs_version
#install modules
npm install

#post-install test scripts.
test_script:
# Output useful info for debugging.
node --version
npm --version

#run tests
npm test

#Don't acutally build.
build: off
